# Generated by Django 4.2.11 on 2024-05-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=40)),
                ('contra', models.CharField(max_length=40)),
                ('ip', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
