# Generated by Django 4.2.11 on 2024-04-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdb',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
