# Generated by Django 4.2.11 on 2024-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariosdb_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdb',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
    ]
