# Generated by Django 4.2.11 on 2024-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_msgsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdb',
            name='alive',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
