# Generated by Django 4.2.11 on 2024-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_usuariosdb_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsdb',
            name='post',
            field=models.CharField(max_length=500),
        ),
    ]
